### ISSUE TITLE
Ballot styles reference a ContestID that is not defined in the Contest array

### ISSUE THREAD

**Issue by mattbeattie** [cwulfman/versasim#1]
I'm using the EDF provided here: 

https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/d4f1361/test_cases/edf_jetsons.json

I'm attempting to generate the ballot markup model for each of the ballot styles. Unfortunately, I found an issue. Specifically, one of the contest IDs seems to be missing. Here’s the error in my code:

```
Unable to find a contest for contestId recXNb4zPrvC1m6Fr
```

I’ve confirmed that contestID `recXNb4zPrvC1m6Fr` is _referenced_ in two of the ballot styles (spaceport and spacetown), but is not defined in the Contest array. Can you help?

**Comment by cwulfman** [comment]
The error was in the business logic: contest `recXNb4zPrvC1m6Fr` (the control board contest) had not been added to the special election in the AirTable interface.  I added it, and the contest object now appears in the report.

Versasim is, of course, meant to be  quick hack, so glitches like this are to be expected.  Going forward, though, I'm sure the TTV developers will do consistency checking to make sure a ballot-style for an election only references contests that are part of the election.
